apiVersion: apps/v1
kind: Deployment
metadata:
  name: user123-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user123-app
  template:
    metadata:
      labels:
        app: user123-app
    spec:
      containers:
      - name: web
        image: docker.io/davoodazarirad/test-kaniko-image:latest
        ports:
        - containerPort: 80
